name: Deploy Backend to Azure App Service

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug repository structure
        run: |
          pwd
          ls -la
          find . -type d -maxdepth 2

      - name: Inject .env from GitHub secrets
        run: |
          # Crear el archivo .env en la ubicación correcta
          mkdir -p backend
          touch backend/.env
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "DB_ENCRYPT=${{ secrets.DB_ENCRYPT }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

      - name: Install dependencies
        run: |
          # Verificar si el directorio existe y luego instalar dependencias
          ls -la
          if [ -d "backend" ]; then
            cd backend
            npm ci
          else
            echo "El directorio backend no existe, asumiendo que estamos en él"
            npm ci
          fi

      - name: Lint
        run: |
          if [ -d "backend" ]; then
            cd backend
          fi
          npm run lint || echo "Lint failed"

      # Cambiamos el método de despliegue para usar credenciales directas en lugar del perfil de publicación
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_BACKEND_NAME }}
          slot-name: 'production'
          package: ./backend