name: Deploy Backend to Azure App Service

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          
      - name: Clean before build
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf build
          
      - name: Clean App Service (Linux)
        run: |
          curl -X POST "https://${{ secrets.AZURE_WEBAPP_BACKEND_NAME }}.scm.azurewebsites.net/api/command" \
          -u "${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE_SOLUSERPWD }}" \
          -H "Content-Type: application/json" \
          --data '{"command": "rm -rf /site/wwwroot/*"}'
          
      - name: Inject .env from GitHub secrets
        run: |
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_ENCRYPT=${{ secrets.DB_ENCRYPT }}" >> .env
          echo "PORT=8080" >> .env
          echo "WEBSITE_NODE_DEFAULT_VERSION=18" >> .env
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "HOST=0.0.0.0" >> .env

      - name: Create startup command file
        run: |
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "npm start" >> startup.sh
          chmod +x startup.sh

      - name: Create deployment files
        run: |
          # Create .deployment file
          echo "[config]" > .deployment
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment
          
          # Create custom startup script
          mkdir -p .azure
          echo "npm start" > .azure/startup.txt

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "Lint failed"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_BACKEND_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE }}
          package: .
          startup-command: "npm start"